type: object
properties:
  apiKey:
    type: string
    x-examples: [ "key" ]
    description: |
      [API-ключ](https://cloud.yandex.com/en/docs/iam/concepts/authorization/api-key) сервисного аккаунта.
      [Инструкция по созданию API-ключ](https://cloud.yandex.com/ru/docs/iam/operations/api-key/create)
      Для доступа к метрикам нелбходимо назначить роль 'monitoring.viewer' для сервис-аккаунта.
  highAvailability:
    description: |
      Ручное управление режимом отказоустойчивости.

      По умолчанию режим отказоустойчивости определяется автоматически. [Подробнее](../../deckhouse-configure-global.html#параметры) про режим отказоустойчивости.
  nodeSelector:
    description: |
      Структура, аналогичная `spec.nodeSelector` Kubernetes pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  tolerations:
    type: array
    description: |
      Структура, аналогичная  `spec.tolerations` в Kubernetes Pod.

      Если ничего не указано или указано `false` — будет [использоваться автоматика](https://deckhouse.io/ru/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
