x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      folderID:
        type: string
      natInstanceName:
        type: string
