{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: yandex-cloud-metrics-exporter
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "yandex-cloud-metrics-exporter")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: yandex-cloud-metrics-exporter
  updatePolicy:
    updateMode: "Initial"
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yandex-cloud-metrics-exporter
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "yandex-cloud-metrics-exporter")) | nindent 2 }}
spec:
  {{- include "helm_lib_deployment_strategy_and_replicas_for_ha" . | nindent 2 }}
  selector:
    matchLabels:
      app: yandex-cloud-metrics-exporter
  template:
    metadata:
      labels:
        app: yandex-cloud-metrics-exporter
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/yandex-cloud-metrics-exporter/yandex-metrics-exporter-app-creds.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
      - name: deckhouse-registry
      {{- include "helm_lib_node_selector" (tuple . "monitoring") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "monitoring") | nindent 6 }}
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "yandex-cloud-metrics-exporter")) | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      containers:
      - name: yandex-cloud-metrics-exporter
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 8 }}
        image: "{{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.monitoringYandexCloud.exporter }}"
        args:
        - "--listen-address=127.0.0.1:8080"
        - "--logger-type=json"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: d8-yandex-metrics-exporter-app-creds
              key: api-key
        - name: FOLDER_ID
          valueFrom:
            secretKeyRef:
              name: d8-yandex-metrics-exporter-app-creds
              key: folder-id
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
        ports:
          - containerPort: 8080
            name: http-metrics
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 12 }}
