---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yandex-cloud-metrics-exporter
  namespace: d8-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:monitoring-yandex-cloud:yandex-cloud-metrics-exporter:d8-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:rbac-proxy
subjects:
  - kind: ServiceAccount
    name: yandex-cloud-metrics-exporter
    namespace: d8-monitoring
